spring:
  application:
    name: pipeline-api
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  structured:
    format:
      console: logstash

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  health:
    db:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/pipeline?allowPublicKeyRetrieval=true&useSSL=false
    username: pipeline
    password: pipeline
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
